-- Cart Table Schema
CREATE TABLE cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id BIGINT NOT NULL,
  total_price DOUBLE PRECISION,
  CONSTRAINT pk_cart PRIMARY KEY (id)
);

-- Item Table Schema
CREATE TABLE item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_id BIGINT,
  quantity BIGINT,
  cart_id BIGINT,
  CONSTRAINT pk_item PRIMARY KEY (id)
);

-- Cart Product Category Schema
CREATE TABLE product_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  category VARCHAR(255),
  sku VARCHAR(255),
  CONSTRAINT pk_product_category PRIMARY KEY (id)
);

-- Product Table Schema
CREATE TABLE product (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  product_category_id BIGINT,
  name VARCHAR(255),
  description VARCHAR(255),
  price DOUBLE PRECISION,
  CONSTRAINT pk_product PRIMARY KEY (id)
);

-- Relationships
ALTER TABLE item ADD CONSTRAINT FK_ITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);
ALTER TABLE item ADD CONSTRAINT FK_ITEM_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);
ALTER TABLE product ADD CONSTRAINT FK_PRODUCT_ON_PRODUCT_CATEGORY FOREIGN KEY (product_category_id) REFERENCES product_category (id);

